#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _ampain_reg(void);
extern void _ampa_reg(void);
extern void _cad_reg(void);
extern void _cadynin_reg(void);
extern void _cadyn_reg(void);
extern void _calcb_reg(void);
extern void _calc_reg(void);
extern void _cal_reg(void);
extern void _cancr_reg(void);
extern void _can_reg(void);
extern void _car_reg(void);
extern void _catcb_reg(void);
extern void _cat_reg(void);
extern void _gabaain_reg(void);
extern void _gabaa_reg(void);
extern void _gabab_reg(void);
extern void _ggap_reg(void);
extern void _hcb_reg(void);
extern void _hin_reg(void);
extern void _h_reg(void);
extern void _ican_reg(void);
extern void _iccb_reg(void);
extern void _iccr_reg(void);
extern void _ikscb_reg(void);
extern void _ikscr_reg(void);
extern void _iks_reg(void);
extern void _kadistcr_reg(void);
extern void _kadist_reg(void);
extern void _kaproxcb_reg(void);
extern void _kaprox_reg(void);
extern void _kcain_reg(void);
extern void _kca_reg(void);
extern void _kct_reg(void);
extern void _kdrcb_reg(void);
extern void _kdrcr_reg(void);
extern void _KdrIND_reg(void);
extern void __kdrin_reg(void);
extern void _kdrin_reg(void);
extern void _kdr_reg(void);
extern void _kdyn_reg(void);
extern void _membrane_noise_reg(void);
extern void _mykca_reg(void);
extern void _naf_at_reg(void);
extern void _nafcr_reg(void);
extern void _NafIND_reg(void);
extern void _nafin_reg(void);
extern void _naf_reg(void);
extern void _nafx_reg(void);
extern void _nap_reg(void);
extern void _netstim_reg(void);
extern void _NMDAb_reg(void);
extern void _nmda_Mg_reg(void);
extern void _NMDA_reg(void);
extern void _NMDA_syn_reg(void);
extern void _poissonStim_reg(void);
extern void _sinclamp_reg(void);
extern void _somacar_reg(void);
extern void _vecstim_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," ampain.mod");
    fprintf(stderr," ampa.mod");
    fprintf(stderr," cad.mod");
    fprintf(stderr," cadynin.mod");
    fprintf(stderr," cadyn.mod");
    fprintf(stderr," calcb.mod");
    fprintf(stderr," calc.mod");
    fprintf(stderr," cal.mod");
    fprintf(stderr," cancr.mod");
    fprintf(stderr," can.mod");
    fprintf(stderr," car.mod");
    fprintf(stderr," catcb.mod");
    fprintf(stderr," cat.mod");
    fprintf(stderr," gabaain.mod");
    fprintf(stderr," gabaa.mod");
    fprintf(stderr," gabab.mod");
    fprintf(stderr," ggap.mod");
    fprintf(stderr," hcb.mod");
    fprintf(stderr," hin.mod");
    fprintf(stderr," h.mod");
    fprintf(stderr," ican.mod");
    fprintf(stderr," iccb.mod");
    fprintf(stderr," iccr.mod");
    fprintf(stderr," ikscb.mod");
    fprintf(stderr," ikscr.mod");
    fprintf(stderr," iks.mod");
    fprintf(stderr," kadistcr.mod");
    fprintf(stderr," kadist.mod");
    fprintf(stderr," kaproxcb.mod");
    fprintf(stderr," kaprox.mod");
    fprintf(stderr," kcain.mod");
    fprintf(stderr," kca.mod");
    fprintf(stderr," kct.mod");
    fprintf(stderr," kdrcb.mod");
    fprintf(stderr," kdrcr.mod");
    fprintf(stderr," KdrIND.mod");
    fprintf(stderr," _kdrin.mod");
    fprintf(stderr," kdrin.mod");
    fprintf(stderr," kdr.mod");
    fprintf(stderr," kdyn.mod");
    fprintf(stderr," membrane_noise.mod");
    fprintf(stderr," mykca.mod");
    fprintf(stderr," naf_at.mod");
    fprintf(stderr," nafcr.mod");
    fprintf(stderr," NafIND.mod");
    fprintf(stderr," nafin.mod");
    fprintf(stderr," naf.mod");
    fprintf(stderr," nafx.mod");
    fprintf(stderr," nap.mod");
    fprintf(stderr," netstim.mod");
    fprintf(stderr," NMDAb.mod");
    fprintf(stderr," nmda_Mg.mod");
    fprintf(stderr," NMDA.mod");
    fprintf(stderr," NMDA_syn.mod");
    fprintf(stderr," poissonStim.mod");
    fprintf(stderr," sinclamp.mod");
    fprintf(stderr," somacar.mod");
    fprintf(stderr," vecstim.mod");
    fprintf(stderr, "\n");
  }
  _ampain_reg();
  _ampa_reg();
  _cad_reg();
  _cadynin_reg();
  _cadyn_reg();
  _calcb_reg();
  _calc_reg();
  _cal_reg();
  _cancr_reg();
  _can_reg();
  _car_reg();
  _catcb_reg();
  _cat_reg();
  _gabaain_reg();
  _gabaa_reg();
  _gabab_reg();
  _ggap_reg();
  _hcb_reg();
  _hin_reg();
  _h_reg();
  _ican_reg();
  _iccb_reg();
  _iccr_reg();
  _ikscb_reg();
  _ikscr_reg();
  _iks_reg();
  _kadistcr_reg();
  _kadist_reg();
  _kaproxcb_reg();
  _kaprox_reg();
  _kcain_reg();
  _kca_reg();
  _kct_reg();
  _kdrcb_reg();
  _kdrcr_reg();
  _KdrIND_reg();
  __kdrin_reg();
  _kdrin_reg();
  _kdr_reg();
  _kdyn_reg();
  _membrane_noise_reg();
  _mykca_reg();
  _naf_at_reg();
  _nafcr_reg();
  _NafIND_reg();
  _nafin_reg();
  _naf_reg();
  _nafx_reg();
  _nap_reg();
  _netstim_reg();
  _NMDAb_reg();
  _nmda_Mg_reg();
  _NMDA_reg();
  _NMDA_syn_reg();
  _poissonStim_reg();
  _sinclamp_reg();
  _somacar_reg();
  _vecstim_reg();
}
