#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/cluster/applications"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/cluster/applications/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/cluster/stefanos/Documents/GitHub/prefrontal-micro/mechanism_simple/x86_64/.libs/libnrnmech.so" "$@"
