#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/cluster/stefanos/Libraries/nrn"
	#NRNHOME="/home/cluster/applications/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/cluster/stefanos/Libraries/nrn/x86_64/bin/"
	#NRNBIN="/home/cluster/applications/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi

"${NRNIV}" -dll "/home/cluster/stefanos/Documents/GitHub/prefrontal-micro/mechanism_simple/x86_64/.libs/libnrnmech.so" "$@"
