#!/bin/sh
# Choose NEURON build to use:
nrn_executable="$1"
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/stefanos/Libraries/${nrn_executable}"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/stefanos/Libraries/${nrn_executable}/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/stefanos/Documents/SourceTree/prefrontal-micro/mechanism_simple/x86_64/.libs/libnrnmech.so" "$@"
echo "Custom envars set by myspecial:"
echo $nrn_executable
echo `which nrniv`
echo "End of custom envars."
